### ISSUE TITLE
error running DNAxiS_webservpy

### ISSUE THREAD

**Issue by MIKEHHQ** [dfu99/dnaxis#1]
I follow the instructions installing redis and the others on ubuntu
However when running: python DNAxiS-websrv.py ,
the error message is shown below, and can u give any advice is it relevant to the config.ini
---------- error message----------
Traceback (most recent call last):
  File "DNAxiS-websrv.py", line 1, in <module>
    from app import app
  File "/home/milk/dnaxis/app/__init__.py", line 5, in <module>
    from app import config
  File "/home/milk/dnaxis/app/config.py", line 33, in <module>
    MAIL_PASSWORD = parser["GENERAL"]["MAIL_PASSWORD"]
  File "/home/dell/anaconda3/envs/py37/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'GENERAL'
(dnaxis) (py37) milk@dell-PowerEdge-T640:~/dnaxis$ python DNAxiS-websrv.py 
Traceback (most recent call last):
  File "DNAxiS-websrv.py", line 1, in <module>
    from app import app
  File "/home/milk/dnaxis/app/__init__.py", line 5, in <module>
    from app import config
  File "/home/milk/dnaxis/app/config.py", line 33, in <module>
    MAIL_PASSWORD = parser["GENERAL"]["MAIL_PASSWORD"]
  File "/home/dell/anaconda3/envs/py37/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'GENERAL'

**Comment by dfu99** [comment]
Hi Mike,

Sorry, I missed this email. Please give me some time to look into it.
Thanks.

Best,
Dan Fu
Reif lab @ Duke University

**Comment by dfu99** [comment]
Hi Mike,

Try replacing your current config parser (app/config.py) with the file from the very first build instead.

Or simply comment out this line https://github.com/dfu99/dnaxis/blob/ed2dc140037a5576601efa73412ffe2631e2deea/app/config.py#L33

**Comment by Mishkorez** [comment]
Hi! I ran into the same error. Unfortunately, both of your tips didn't work. After the correction, the same errors begin to occur in the following lines. Help, pls!

**Comment by moyangdan** [comment]
Hi! I ran into the same error. Unfortunately, both of your tips didn't work. After the correction, the same errors begin to occur in the following lines. Help, pls!

**Comment by moyangdan** [comment]
Traceback (most recent call last):
  File "DNAxiS-websrv.py", line 1, in <module>
    from app import app
  File "D:\dnaxis-main\dnaxis-main\app\__init__.py", line 5, in <module>
    from app import config
  File "D:\dnaxis-main\dnaxis-main\app\config.py", line 37, in <module>
    DEBUG_MSGS = bool(int(parser["GENERAL"]["DEBUG_MSGS"]))
  File "C:\Users\MoYangdan\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'GENERAL'

**Comment by dfu99** [comment]
Hi, I think it was not made clear that sample_config.ini must be renamed to config.ini, which is where I believe this error is coming from. Sorry about that. Please try renaming it or pull [#bb4503e](https://github.com/dfu99/dnaxis/blob/bb4503e74a45f4101345ea0aedf7d32dc751d68d/config.ini) because there are some keyword changes too.

**Comment by moyangdan** [comment]
> Hi, I think it was not made clear that sample_config.ini must be renamed to config.ini, which is where I believe this error is coming from. Sorry about that. Please try renaming it or pull [#bb4503e](https://github.com/dfu99/dnaxis/blob/bb4503e74a45f4101345ea0aedf7d32dc751d68d/config.ini) because there are some keyword changes too.

thanks,bro.I ran successfully.
