### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by ghost** [dfu99/dnaxis#2]
Hi,

When running the server, I'm getting this error: 
* Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 133-098-938
127.0.0.1 - - [10/Feb/2024 11:55:25] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/redis/connection.py", line 614, in connect
    sock = self.retry.call_with_retry(
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/redis/connection.py", line 615, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/redis/connection.py", line 680, in _connect
    raise err
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/redis/connection.py", line 668, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/flask/app.py", line 1508, in finalize_request
    response = self.process_response(response)
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/flask/app.py", line 2005, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/flask_session/sessions.py", line 158, in save_session
    self.redis.setex(name=self.key_prefix + session.sid, value=val,
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/redis/commands/core.py", line 2233, in setex
    return self.execute_command("SETEX", name, time, value)
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/redis/client.py", line 1224, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/redis/connection.py", line 1392, in get_connection
    connection.connect()
  File "/Users/geokir/dnaxis/lib/python3.9/site-packages/redis/connection.py", line 620, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
127.0.0.1 - - [10/Feb/2024 11:55:25] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [10/Feb/2024 11:55:25] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [10/Feb/2024 11:55:25] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [10/Feb/2024 11:55:25] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -

Could you please help with this?

**Comment by dfu99** [comment]
Hi,

This looks like redis is not installed/running.

Here are the instructions to install/run it on Mac: https://redis.io/docs/install/install-redis/install-redis-on-linux/
